### ISSUE TITLE
Failed to activate the slima package

### ISSUE THREAD

**Issue by itmuckel** [neil-lindquist/SLIMA#23]
I just tried to install Slima from within Atom and got the error below. Any advice?

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Windows 10
**Thrown From**: [slima](https://github.com/neil-lindquist/slima) package 2.2.0

### Stack Trace

Failed to activate the slima package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StatusBarView.addLeftTile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:995367)
    at ProfilerView.module.exports.ProfilerView.attach (/packages/slima/lib/slima-profiler-view.coffee:60:16)
    at SlimaView.module.exports.SlimaView.setStatusBar (/packages/slima/lib/slima-view.coffee:41:18)
    at Object.consumeStatusBar (/packages/slima/lib/slima.coffee:181:12)
    at Provider.provide (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:1124313)
    at ServiceHub.consume (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3536497)
    at Package.activateServices (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3544729)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3541484)
    at measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540808)
    at Package.measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3538418)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540668)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540611)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381612)
    at ~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:935623
    at r (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:930229)
    at n (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:1127220)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:1127426)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

### Commands

```
  2x -3:48.1.0 vim-mode-plus:move-up (input.hidden-input)
     -3:47.4.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -3:46.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -3:46.2.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
language-lisp 0.2.0 
lisp-paredit 0.6.0 
slima 2.2.0 
vim-mode-plus 1.36.0 
```

**Comment by uUJsd7PX** [comment]
Have you tried with vim-mode-plus disabled?

**Comment by neil-lindquist** [comment]
I've had this stack trace show up once is a blue moon, but I've never been able to reproduce it. This occurs when Atom starts, correct?  And does it happen everytime?

**Comment by itmuckel** [comment]
I resolved this by simply restarting Atom.

Additional info: I had atom-slime installed previously, uninstalled atom-slime and installed slima in the same session.

**Comment by neil-lindquist** [comment]
Good to hear you are able to work around it.
It sounds like there's an issue with either removing atom-slime or activating slima in an established runtime. When I get a chance I'll look at it, but I might just resort to catching the error and asking the user to restart Atom.

**Comment by itmuckel** [comment]
Well, since this seems to be a fork of atom-slime maybe there's a namespace collision anywhere or something like that?

**Comment by neil-lindquist** [comment]
Yea, I'm guessing it's either a namespace collision or one/both of the packages aren't using the status bar quite right. But, given that this seems to only occur when uninstalling Atom-Slime and installing SLIMA in the same session, I'm just going to improve the error message when this happens and not try to debug this issue.
