### ISSUE TITLE
Uncaught Error: null

### ISSUE THREAD

**Issue by sayantika98** [neil-lindquist/SLIMA#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [slima](https://github.com/neil-lindquist/slima) package 2.4.1

### Stack Trace

Uncaught Error: null

```
At C:\Users\sayan\.atom\packages\slima\node_modules\temporary\lib\file.js:100

Error: null
    at /packages/slima/node_modules/temporary/lib/file.js:100:73
    at FSReqWrap.oncomplete (fs.js:141:20)
```

### Commands

```
     -6:37.2.0 command-palette:toggle (input.hidden-input)
     -6:30.5.0 slime:connect (input.hidden-input)
     -5:30.2.0 command-palette:toggle (input.hidden-input)
     -5:26.8.0 slime:connect (input.hidden-input)
 11x -5:05.2.0 lisp-paredit:delete-backwards (input.hidden-input)
     -4:58.7.0 command-palette:toggle (input.hidden-input)
     -4:55.6.0 slime:start (input.hidden-input)
     -4:45.7.0 command-palette:toggle (input.hidden-input)
     -4:37.2.0 slime:start (input.hidden-input)
     -2:46.1.0 command-palette:toggle (input.hidden-input)
     -2:38 slime:start (input.hidden-input)
     -1:55.3.0 lisp-paredit:newline (input.hidden-input)
     -1:52.8.0 core:save (input.hidden-input)
     -1:48.2.0 editor:newline-below (input.hidden-input)
     -1:39 command-palette:toggle (input.hidden-input)
     -1:35.3.0 slime:restart (input.hidden-input)
```

### Non-Core Packages

```
atom-slime 2.8.0 
Hydrogen 2.14.1 
language-common-lisp 0.9.5 
language-lisp 0.2.0 
lisp-paredit 0.7.0 
list-edit 1.0.1 
parinfer 1.23.0 
slima 2.4.1 
```

**Comment by neil-lindquist** [comment]
Do you have a set of steps that can reproduce this error?  Or what you were doing when this error occured?

**Comment by neil-lindquist** [comment]
I haven't been able to replicate this error, so I'm going to close this issue unless someone can provide me with the steps needed to cause the error.

**Comment by mmontone** [comment]
I've just came across this error when trying to uninstall SLIMA. I tried to uninstall from Atom Settings.

```
Uncaught Error: null

/mnt/e6b00b8f-9dad-4bf4-bd40-34b1e6d31f0a/home/marian/.atom/packages/slima/node_modules/temporary/lib/file.js:100
Hide Stack Trace
Error: null
    at /mnt/e6b00b8f-9dad-4bf4-bd40-34b1e6d31f0a/home/marian/.atom/packages/slima/node_modules/temporary/lib/file.js:100:73
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Comment by neil-lindquist** [comment]
I think I've fixed this issue in the release candidate for 2.5.0.
