### ISSUE TITLE
REPL crashing

### ISSUE THREAD

**Issue by josharmenta** [neil-lindquist/SLIMA#57]
Hi Neil,

Getting this even tho I can see the file on path. Seems to happen when I hit the hotkey for Save; I'm on MacOS.

### Versions

**Atom**: 1.102.2023021606 x64
**Electron**: 12.2.3
**OS**: macOS 12.6
**Thrown From**: [slima](https://github.com/neil-lindquist/slima) package 2.8.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/joshuaarmenta/repl.lisp-repl'

```
At internal/fs/utils.js:307

Error: ENOENT: no such file or directory, unlink '/Users/joshuaarmenta/repl.lisp-repl'
    at Object.unlinkSync (fs.js:1210:3)
    at REPLView.module.exports.REPLView.destroy (/packages/slima/lib/slima-repl-view.coffee:670:10)
    at REPLView.destroy (/packages/slima/lib/slima-repl-view.coffee:1:1)
    at SlimaView.module.exports.SlimaView.destroyRepl (/packages/slima/lib/slima-view.coffee:30:13)
    at /packages/slima/lib/slima.coffee:235:17)
    at /packages/slima/node_modules/swank-client/lib/client.js:78:22)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.47 
language-common-lisp 0.9.5 
lisp-paredit 0.8.0 
slima 2.8.1 
```

**Comment by josharmenta** [comment]
Oh I completely forgot about this!!Yes I figured it out.I was working with CLOG and the CLOG Builder started from SLIMA. Turns out CLOG Builder kind of broke something in that repl file.It seemed to go away after I upgraded to the latest Pulsar and cleaned out all those temp and plist files.I don’t know why CLOG would be able to box the system like that unless I did something stupid which is highly likely, but it seems to be gone now. I’ll reopen later if this comes back but I have a feeling that there was a race condition between SLIMA and CLOG that seems to have been resolved by the Pulsar bug fixes.Sent from my iPhoneOn Mar 8, 2023, at 18:45, Neil Lindquist ***@***.***> wrote:﻿
Does it happen if you restart Pulsar, open a new SLIMA REPL and immediately save?
If you manually delete the file before starting SLIMA, does the error message still occur?
repl.lisp-repl is a cludge to work around some Atom/Pulsar limitations.  It's suppose to act as if there isn't actually a file, but it's kind of delicate.
